package by.etc.karamach.controller.command;

public enum CommandName {
    SIGN_IN, REGISTRATION, NO_SUCH_COMMAND, GET_TESTS, GET_MY_TESTS, CREATE_TEST, LOGOUT, DELETE_TEST, EDIT_TEST,
    EDIT_QUESTION, DELETE_QUESTION, EDIT_ANSWER, UPDATE_ANSWER, CREATE_ANSWER, DELETE_ANSWER, CHANGE_QUESTION_NAME,
    CREATE_QUESTION, CHANGE_TEST_NAME, PUBLISH_TEST, TAKE_TEST, START_TEST, MAKE_CHOICE, GET_NEXT_QUESTION
}
