-- MySQL Script generated by MySQL Workbench
-- Thu Jan 17 19:46:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
CREATE DATABASE JWD_WebProject;

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JWD_WebProject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JWD_WebProject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JWD_WebProject`
  DEFAULT CHARACTER SET utf8;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `JWD_WebProject`;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`users` (
  `id`           INT(11)      NOT NULL AUTO_INCREMENT,
  `email`        VARCHAR(100) NOT NULL DEFAULT '',
  `password`     VARCHAR(100) NOT NULL DEFAULT '',
  `access_level` INT(11)      NOT NULL,
  `name`         VARCHAR(100) NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`users` (`id` ASC) VISIBLE;

CREATE UNIQUE INDEX `email_UNIQUE`
  ON `JWD_WebProject`.`users` (`email` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`tests` (
  `id`       INT(11)      NOT NULL AUTO_INCREMENT,
  `name`     VARCHAR(100) NOT NULL DEFAULT '',
  `status`   VARCHAR(100) NOT NULL DEFAULT '',
  `users_id` INT(11)      NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_tests_users`
  FOREIGN KEY (`users_id`)
  REFERENCES `JWD_WebProject`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`tests` (`id` ASC) VISIBLE;

CREATE INDEX `fk_tests_users_idx`
  ON `JWD_WebProject`.`tests` (`users_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`questions` (
  `id`          INT          NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(100) NOT NULL DEFAULT '',
  `owner_id`    INT(11)      NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_questions_users1`
  FOREIGN KEY (`owner_id`)
  REFERENCES `JWD_WebProject`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`questions` (`id` ASC) VISIBLE;

CREATE INDEX `fk_questions_users1_idx`
  ON `JWD_WebProject`.`questions` (`owner_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`answers` (
  `id`           INT         NOT NULL AUTO_INCREMENT,
  `description`  VARCHAR(30) NOT NULL DEFAULT '',
  `isRight`      TINYINT(1)  NOT NULL DEFAULT 0,
  `questions_id` INT         NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_answers_questions1`
  FOREIGN KEY (`questions_id`)
  REFERENCES `JWD_WebProject`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`answers` (`id` ASC) VISIBLE;

CREATE INDEX `fk_answers_questions1_idx`
  ON `JWD_WebProject`.`answers` (`questions_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`tests_has_questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`tests_has_questions` (
  `tests_id`     INT(11) NOT NULL,
  `questions_id` INT     NOT NULL,
  CONSTRAINT `fk_tests_has_questions_tests1`
  FOREIGN KEY (`tests_id`)
  REFERENCES `JWD_WebProject`.`tests` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tests_has_questions_questions1`
  FOREIGN KEY (`questions_id`)
  REFERENCES `JWD_WebProject`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE INDEX `fk_tests_has_questions_tests1_idx`
  ON `JWD_WebProject`.`tests_has_questions` (`tests_id` ASC) VISIBLE;

CREATE INDEX `fk_tests_has_questions_questions1_idx`
  ON `JWD_WebProject`.`tests_has_questions` (`questions_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`grades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`grades` (
  `id`          INT        NOT NULL AUTO_INCREMENT,
  `degree`      INT        NOT NULL DEFAULT 0,
  `finish_time` DATETIME   NULL,
  `is_finished` TINYINT(1) NULL     DEFAULT 0,
  `users_id`    INT(11)    NOT NULL,
  `tests_id`    INT(11)    NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_grades_users1`
  FOREIGN KEY (`users_id`)
  REFERENCES `JWD_WebProject`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grades_tests1`
  FOREIGN KEY (`tests_id`)
  REFERENCES `JWD_WebProject`.`tests` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`grades` (`id` ASC) VISIBLE;

CREATE INDEX `fk_grades_users1_idx`
  ON `JWD_WebProject`.`grades` (`users_id` ASC) VISIBLE;

CREATE INDEX `fk_grades_tests1_idx`
  ON `JWD_WebProject`.`grades` (`tests_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `JWD_WebProject`.`choices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JWD_WebProject`.`choices` (
  `id`          INT NOT NULL AUTO_INCREMENT,
  `grade_id`    INT NOT NULL,
  `answer_id`   INT NOT NULL,
  `question_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_choices_grades1`
  FOREIGN KEY (`grade_id`)
  REFERENCES `JWD_WebProject`.`grades` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_choices_answers1`
  FOREIGN KEY (`answer_id`)
  REFERENCES `JWD_WebProject`.`answers` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_choices_questions1`
  FOREIGN KEY (`question_id`)
  REFERENCES `JWD_WebProject`.`questions` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION
)
  ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE`
  ON `JWD_WebProject`.`choices` (`id` ASC) VISIBLE;

CREATE INDEX `fk_choices_grades1_idx`
  ON `JWD_WebProject`.`choices` (`grade_id` ASC) VISIBLE;

CREATE INDEX `fk_choices_answers1_idx`
  ON `JWD_WebProject`.`choices` (`answer_id` ASC) VISIBLE;

CREATE INDEX `fk_choices_questions1_idx`
  ON `JWD_WebProject`.`choices` (`question_id` ASC) VISIBLE;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
